import type { GrantProgram } from "./types";

export const GRANT_PROGRAMS: GrantProgram[] = [
  {
    id: "anthropic-startup",
    name: "Anthropic Startup Program",
    funder: "Anthropic",
    awardRange: "$25K API credits",
    eligibilitySummary:
      "Early-stage startups building products or services powered by Claude AI. Must be pre-Series B.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion", "Other"],
    geographies: ["Global"],
    stages: ["Pre-seed", "Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://www.anthropic.com/startups",
    submissionType: "portal",
    portalLabel: "Apply at anthropic.com/startups",
  },
  {
    id: "anthropic-nonprofit",
    name: "Anthropic Nonprofit Credits",
    funder: "Anthropic",
    awardRange: "Up to $25K API credits",
    eligibilitySummary:
      "Registered nonprofits using Claude AI for social-impact applications. 501(c)(3) or equivalent required.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion", "Other"],
    geographies: ["Global"],
    stages: ["Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.anthropic.com/nonprofits",
    submissionType: "portal",
    portalLabel: "Apply at anthropic.com/nonprofits",
  },
  {
    id: "gates-grand-challenges",
    name: "Gates Foundation Grand Challenges",
    funder: "Bill & Melinda Gates Foundation",
    awardRange: "$100K–$1M",
    eligibilitySummary:
      "Breakthrough innovations in global health, agriculture, and poverty reduction in low- and middle-income countries. Open to organizations worldwide.",
    focusAreas: ["Healthcare", "Agriculture", "Education"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Global"],
    stages: ["Pre-seed", "Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://gcgh.grandchallenges.org",
    submissionType: "portal",
    portalLabel: "Apply at grandchallenges.org",
  },
  {
    id: "wellcome-innovations",
    name: "Wellcome Trust Innovations",
    funder: "Wellcome Trust",
    awardRange: "£50K–£500K",
    eligibilitySummary:
      "Health innovation projects in low- and middle-income countries with strong scientific evidence base. Open to nonprofits and for-profits.",
    focusAreas: ["Healthcare"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://wellcome.org/grant-funding/schemes",
    submissionType: "portal",
    portalLabel: "Apply at wellcome.org",
  },
  {
    id: "usaid-div",
    name: "USAID Development Innovation Ventures",
    funder: "USAID",
    awardRange: "$25K–$15M",
    eligibilitySummary:
      "Evidence-based solutions to global development challenges with rigorous testing approach. Open to all organization types with phased funding.",
    focusAreas: ["Healthcare", "Agriculture", "Education", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Pre-seed", "Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.usaid.gov/div",
    submissionType: "email",
    submissionEmail: "div@usaid.gov",
    portalLabel: "Email div@usaid.gov",
  },
  {
    id: "nih-sttr-sbir",
    name: "NIH STTR/SBIR Phase I",
    funder: "National Institutes of Health",
    awardRange: "$300K",
    eligibilitySummary:
      "US-based small businesses commercializing health technology with a research institution partner. Must have principal researcher affiliation.",
    focusAreas: ["Healthcare"],
    geographies: ["Global"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://grants.nih.gov/funding/sbir",
    submissionType: "portal",
    portalLabel: "Submit via Research.gov",
  },
  {
    id: "google-org-impact",
    name: "Google.org Impact Challenge",
    funder: "Google.org",
    awardRange: "$250K",
    eligibilitySummary:
      "Tech-enabled solutions to pressing social and environmental challenges. Registered nonprofits or social enterprises in eligible countries.",
    focusAreas: ["Healthcare", "Education", "Climate", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "Southeast Asia", "South Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://impactchallenge.withgoogle.com",
    submissionType: "portal",
    portalLabel: "Apply at impactchallenge.withgoogle.com",
  },
  {
    id: "skoll-foundation",
    name: "Skoll Foundation Award",
    funder: "Skoll Foundation",
    awardRange: "$1.25M over 3 years",
    eligibilitySummary:
      "Systems-changing social entrepreneurs with proven models scaling to address root causes of inequality. Invite-only; nominations considered.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://skoll.org/about/nominations",
    submissionType: "invitation",
    portalLabel: "Submit a nomination at skoll.org",
  },
  {
    id: "echoing-green",
    name: "Echoing Green Fellowship",
    funder: "Echoing Green",
    awardRange: "$90K over 2 years",
    eligibilitySummary:
      "Early-stage social entrepreneurs launching bold new ideas. Fellows receive funding plus leadership development and network support.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://echoinggreen.org/fellowship",
    submissionType: "portal",
    portalLabel: "Apply at echoinggreen.org/fellowship",
  },
  {
    id: "omidyar-network",
    name: "Omidyar Network",
    funder: "Omidyar Network",
    awardRange: "$1M+",
    eligibilitySummary:
      "Tech-enabled social impact ventures with potential for systemic change. Invests in both nonprofits and for-profits at growth stage.",
    focusAreas: ["Education", "Financial Inclusion", "Healthcare", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://omidyar.com/contact",
    submissionType: "email",
    submissionEmail: "contact@omidyar.com",
    portalLabel: "Email contact@omidyar.com",
  },
  {
    id: "mozilla-tech-fund",
    name: "Mozilla Foundation Tech Fund",
    funder: "Mozilla Foundation",
    awardRange: "$50K–$150K",
    eligibilitySummary:
      "Open-source technology projects that advance a healthy internet for the public benefit. Preference for nonprofits and open-tech projects.",
    focusAreas: ["Education", "Healthcare", "Other"],
    geographies: ["Global"],
    stages: ["Pre-seed", "Seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://foundation.mozilla.org/en/what-we-fund/awards",
    submissionType: "portal",
    portalLabel: "Apply at foundation.mozilla.org",
  },
  {
    id: "macarthur-100change",
    name: "MacArthur Foundation 100&Change",
    funder: "MacArthur Foundation",
    awardRange: "$100M (single grant)",
    eligibilitySummary:
      "Single transformative project with the potential to solve a critical problem of our time. Open to nonprofits and for-profits globally.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.macfound.org/programs/100change",
    submissionType: "portal",
    portalLabel: "Apply at macfound.org",
  },
  {
    id: "rockefeller",
    name: "Rockefeller Foundation Grants",
    funder: "The Rockefeller Foundation",
    awardRange: "$100K–$5M",
    eligibilitySummary:
      "Innovations addressing health, food security, and energy access in developing countries. Focus on scalable solutions with measurable outcomes.",
    focusAreas: ["Healthcare", "Agriculture", "Climate", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.rockefellerfoundation.org/grants",
    submissionType: "email",
    submissionEmail: "grants@rockefellerfoundation.org",
    portalLabel: "Email grants@rockefellerfoundation.org",
  },
  {
    id: "menlo-anthology",
    name: "Menlo Anthology Fund",
    funder: "Menlo Ventures & Anthology",
    awardRange: "$100K+ equity investment",
    eligibilitySummary:
      "AI-native startups building commercial products with Anthropic Claude. Early-stage, equity investment. Particularly interested in enterprise AI applications.",
    focusAreas: ["Healthcare", "Education", "Financial Inclusion", "Other"],
    geographies: ["Global"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://anthology.vc",
    submissionType: "email",
    submissionEmail: "portfolio@anthology.vc",
    portalLabel: "Email portfolio@anthology.vc",
  },
  {
    id: "mcgovern",
    name: "Patrick J. McGovern Foundation",
    funder: "Patrick J. McGovern Foundation",
    awardRange: "Up to $500K",
    eligibilitySummary:
      "Data and AI solutions for lasting positive change in health, food, learning, and financial wellness. Must demonstrate equity-centered design.",
    focusAreas: ["Healthcare", "Education", "Agriculture", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.mcgovern.org/what-we-fund",
    submissionType: "portal",
    portalLabel: "Apply at mcgovern.org",
  },
];
