import type { GrantProgram } from "./types";

export const GRANT_PROGRAMS: GrantProgram[] = [
  {
    id: "anthropic-startup",
    name: "Anthropic Startup Program",
    funder: "Anthropic",
    awardRange: "$25K API credits",
    eligibilitySummary:
      "Early-stage startups building products or services powered by Claude AI. Must be pre-Series B.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion", "Other"],
    geographies: ["Global"],
    stages: ["Pre-seed", "Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://www.anthropic.com/startups",
    submissionType: "portal",
    portalLabel: "Apply at anthropic.com/startups",
  },
  {
    id: "anthropic-nonprofit",
    name: "Anthropic Nonprofit Credits",
    funder: "Anthropic",
    awardRange: "Up to $25K API credits",
    eligibilitySummary:
      "Registered nonprofits using Claude AI for social-impact applications. 501(c)(3) or equivalent required.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion", "Other"],
    geographies: ["Global"],
    stages: ["Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.anthropic.com/nonprofits",
    submissionType: "portal",
    portalLabel: "Apply at anthropic.com/nonprofits",
  },
  {
    id: "gates-grand-challenges",
    name: "Gates Foundation Grand Challenges",
    funder: "Bill & Melinda Gates Foundation",
    awardRange: "$100K–$1M",
    eligibilitySummary:
      "Breakthrough innovations in global health, agriculture, and poverty reduction in low- and middle-income countries. Open to organizations worldwide.",
    focusAreas: ["Healthcare", "Agriculture", "Education"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Global"],
    stages: ["Pre-seed", "Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://gcgh.grandchallenges.org",
    submissionType: "portal",
    portalLabel: "Apply at grandchallenges.org",
  },
  {
    id: "wellcome-innovations",
    name: "Wellcome Trust Innovations",
    funder: "Wellcome Trust",
    awardRange: "£50K–£500K",
    eligibilitySummary:
      "Health innovation projects in low- and middle-income countries with strong scientific evidence base. Open to nonprofits and for-profits.",
    focusAreas: ["Healthcare"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://wellcome.org/grant-funding/schemes",
    submissionType: "portal",
    portalLabel: "Apply at wellcome.org",
  },
  {
    id: "usaid-div",
    name: "USAID Development Innovation Ventures",
    funder: "USAID",
    awardRange: "$25K–$15M",
    eligibilitySummary:
      "Evidence-based solutions to global development challenges with rigorous testing approach. Open to all organization types with phased funding.",
    focusAreas: ["Healthcare", "Agriculture", "Education", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Pre-seed", "Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.usaid.gov/div",
    submissionType: "email",
    submissionEmail: "div@usaid.gov",
    portalLabel: "Email div@usaid.gov",
  },
  {
    id: "nih-sttr-sbir",
    name: "NIH STTR/SBIR Phase I",
    funder: "National Institutes of Health",
    awardRange: "$300K",
    eligibilitySummary:
      "US-based small businesses commercializing health technology with a research institution partner. Must have principal researcher affiliation.",
    focusAreas: ["Healthcare"],
    geographies: ["Global"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://grants.nih.gov/funding/sbir",
    submissionType: "portal",
    portalLabel: "Submit via Research.gov",
  },
  {
    id: "google-org-impact",
    name: "Google.org Impact Challenge",
    funder: "Google.org",
    awardRange: "$250K",
    eligibilitySummary:
      "Tech-enabled solutions to pressing social and environmental challenges. Registered nonprofits or social enterprises in eligible countries.",
    focusAreas: ["Healthcare", "Education", "Climate", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "Southeast Asia", "South Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://impactchallenge.withgoogle.com",
    submissionType: "portal",
    portalLabel: "Apply at impactchallenge.withgoogle.com",
  },
  {
    id: "skoll-foundation",
    name: "Skoll Foundation Award",
    funder: "Skoll Foundation",
    awardRange: "$1.25M over 3 years",
    eligibilitySummary:
      "Systems-changing social entrepreneurs with proven models scaling to address root causes of inequality. Invite-only; nominations considered.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://skoll.org/about/nominations",
    submissionType: "invitation",
    portalLabel: "Submit a nomination at skoll.org",
  },
  {
    id: "echoing-green",
    name: "Echoing Green Fellowship",
    funder: "Echoing Green",
    awardRange: "$90K over 2 years",
    eligibilitySummary:
      "Early-stage social entrepreneurs launching bold new ideas. Fellows receive funding plus leadership development and network support.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://echoinggreen.org/fellowship",
    submissionType: "portal",
    portalLabel: "Apply at echoinggreen.org/fellowship",
  },
  {
    id: "omidyar-network",
    name: "Omidyar Network",
    funder: "Omidyar Network",
    awardRange: "$1M+",
    eligibilitySummary:
      "Tech-enabled social impact ventures with potential for systemic change. Invests in both nonprofits and for-profits at growth stage.",
    focusAreas: ["Education", "Financial Inclusion", "Healthcare", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://omidyar.com/contact",
    submissionType: "email",
    submissionEmail: "contact@omidyar.com",
    portalLabel: "Email contact@omidyar.com",
  },
  {
    id: "mozilla-tech-fund",
    name: "Mozilla Foundation Tech Fund",
    funder: "Mozilla Foundation",
    awardRange: "$50K–$150K",
    eligibilitySummary:
      "Open-source technology projects that advance a healthy internet for the public benefit. Preference for nonprofits and open-tech projects.",
    focusAreas: ["Education", "Healthcare", "Other"],
    geographies: ["Global"],
    stages: ["Pre-seed", "Seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://foundation.mozilla.org/en/what-we-fund/awards",
    submissionType: "portal",
    portalLabel: "Apply at foundation.mozilla.org",
  },
  {
    id: "macarthur-100change",
    name: "MacArthur Foundation 100&Change",
    funder: "MacArthur Foundation",
    awardRange: "$100M (single grant)",
    eligibilitySummary:
      "Single transformative project with the potential to solve a critical problem of our time. Open to nonprofits and for-profits globally.",
    focusAreas: ["Healthcare", "Education", "Climate", "Agriculture", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.macfound.org/programs/100change",
    submissionType: "portal",
    portalLabel: "Apply at macfound.org",
  },
  {
    id: "rockefeller",
    name: "Rockefeller Foundation Grants",
    funder: "The Rockefeller Foundation",
    awardRange: "$100K–$5M",
    eligibilitySummary:
      "Innovations addressing health, food security, and energy access in developing countries. Focus on scalable solutions with measurable outcomes.",
    focusAreas: ["Healthcare", "Agriculture", "Climate", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.rockefellerfoundation.org/grants",
    submissionType: "email",
    submissionEmail: "grants@rockefellerfoundation.org",
    portalLabel: "Email grants@rockefellerfoundation.org",
  },
  {
    id: "menlo-anthology",
    name: "Menlo Anthology Fund",
    funder: "Menlo Ventures & Anthology",
    awardRange: "$100K+ equity investment",
    eligibilitySummary:
      "AI-native startups building commercial products with Anthropic Claude. Early-stage, equity investment. Particularly interested in enterprise AI applications.",
    focusAreas: ["Healthcare", "Education", "Financial Inclusion", "Other"],
    geographies: ["Global"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://anthology.vc",
    submissionType: "email",
    submissionEmail: "portfolio@anthology.vc",
    portalLabel: "Email portfolio@anthology.vc",
  },
  {
    id: "mcgovern",
    name: "Patrick J. McGovern Foundation",
    funder: "Patrick J. McGovern Foundation",
    awardRange: "Up to $500K",
    eligibilitySummary:
      "Data and AI solutions for lasting positive change in health, food, learning, and financial wellness. Must demonstrate equity-centered design.",
    focusAreas: ["Healthcare", "Education", "Agriculture", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.mcgovern.org/what-we-fund",
    submissionType: "portal",
    portalLabel: "Apply at mcgovern.org",
  },

  // ── US Federal ──────────────────────────────────────────────────────────────
  {
    id: "nsf-sbir",
    name: "NSF SBIR/STTR Phase I",
    funder: "National Science Foundation",
    awardRange: "Up to $275K",
    eligibilitySummary:
      "US-based small businesses with fewer than 500 employees commercializing high-risk, deep-tech innovations with strong scientific merit.",
    focusAreas: ["Healthcare", "Climate", "Agriculture", "Education", "Other"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://seedfund.nsf.gov",
    submissionType: "portal",
    portalLabel: "Apply at seedfund.nsf.gov",
  },
  {
    id: "doe-sbir",
    name: "DOE SBIR/STTR Program",
    funder: "US Department of Energy",
    awardRange: "$200K–$1.7M",
    eligibilitySummary:
      "US small businesses advancing energy technologies including clean energy, grid modernization, and energy efficiency. Phase I up to $200K, Phase II up to $1.7M.",
    focusAreas: ["Climate", "Other"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://www.energy.gov/science/sbir",
    submissionType: "portal",
    portalLabel: "Apply at science.osti.gov/sbir",
  },
  {
    id: "usda-sbir",
    name: "USDA SBIR/STTR Program",
    funder: "US Department of Agriculture",
    awardRange: "Up to $175K (Phase I), $450K (Phase II)",
    eligibilitySummary:
      "US small businesses innovating in agriculture, food systems, rural development, and natural resources. Must have primary place of business in the US.",
    focusAreas: ["Agriculture", "Climate", "Other"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://nifa.usda.gov/program/small-business-innovation-research-program-sbir",
    submissionType: "portal",
    portalLabel: "Apply via Grants.gov",
  },
  {
    id: "epa-sbir",
    name: "EPA SBIR Program",
    funder: "US Environmental Protection Agency",
    awardRange: "Up to $100K (Phase I), $400K (Phase II)",
    eligibilitySummary:
      "US small businesses developing environmental technologies, pollution prevention, and sustainable solutions. Must address an EPA research priority.",
    focusAreas: ["Climate", "Agriculture", "Other"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://www.epa.gov/sbir",
    submissionType: "portal",
    portalLabel: "Apply at epa.gov/sbir",
  },
  {
    id: "hhs-acf",
    name: "HHS ACF Innovation Fund",
    funder: "US Dept. of Health and Human Services — ACF",
    awardRange: "$500K–$5M",
    eligibilitySummary:
      "Nonprofits and social enterprises addressing poverty, child welfare, and family stability through evidence-based or innovative service models.",
    focusAreas: ["Healthcare", "Education", "Financial Inclusion"],
    geographies: ["United States"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.acf.hhs.gov/grants",
    submissionType: "portal",
    portalLabel: "Apply via Grants.gov",
  },
  {
    id: "eda-build-to-scale",
    name: "EDA Build to Scale Program",
    funder: "US Economic Development Administration",
    awardRange: "$500K–$3M",
    eligibilitySummary:
      "Organizations that accelerate scalable startups and strengthen regional innovation ecosystems. Includes Venture Challenge and Capital Challenge tracks.",
    focusAreas: ["Other", "Financial Inclusion"],
    geographies: ["United States"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://eda.gov/funding/programs/build-to-scale",
    submissionType: "portal",
    portalLabel: "Apply at eda.gov",
  },

  // ── International Development ────────────────────────────────────────────────
  {
    id: "world-bank-development-marketplace",
    name: "World Bank Development Marketplace",
    funder: "World Bank Group",
    awardRange: "$100K–$200K",
    eligibilitySummary:
      "Innovative, scalable solutions to development challenges in World Bank client countries. Open to NGOs, social enterprises, and research institutions.",
    focusAreas: ["Healthcare", "Agriculture", "Education", "Financial Inclusion", "Climate"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.worldbank.org/en/programs/development-marketplace",
    submissionType: "portal",
    portalLabel: "Apply at worldbank.org",
  },
  {
    id: "undp-accelerator-labs",
    name: "UNDP Accelerator Labs",
    funder: "United Nations Development Programme",
    awardRange: "$50K–$500K",
    eligibilitySummary:
      "Local innovators tackling SDG challenges in 91 countries. Labs co-invest in grassroots solutions with potential for national scaling.",
    focusAreas: ["Healthcare", "Agriculture", "Climate", "Education", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Pre-seed", "Seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://acceleratorlabs.undp.org",
    submissionType: "portal",
    portalLabel: "Apply at acceleratorlabs.undp.org",
  },
  {
    id: "eu-horizon-europe",
    name: "EU Horizon Europe — EIC Accelerator",
    funder: "European Commission",
    awardRange: "Up to €2.5M grant + €15M equity",
    eligibilitySummary:
      "Breakthrough innovations from SMEs and startups in EU member states or associated countries. Targets high-risk, high-impact deep-tech and social innovation.",
    focusAreas: ["Healthcare", "Climate", "Agriculture", "Education", "Other"],
    geographies: ["Global"],
    stages: ["Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
    submissionType: "portal",
    portalLabel: "Apply at eic.ec.europa.eu",
  },
  {
    id: "giz-innovation-fund",
    name: "GIZ Innovation Fund",
    funder: "Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ)",
    awardRange: "€100K–€500K",
    eligibilitySummary:
      "Scalable, market-based solutions to development challenges in GIZ partner countries. Open to startups, NGOs, and research organizations.",
    focusAreas: ["Healthcare", "Agriculture", "Climate", "Education", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.giz.de/en/mediacenter/innovationchallenge.html",
    submissionType: "portal",
    portalLabel: "Apply at giz.de",
  },
  {
    id: "uk-fcdo-ayrton-fund",
    name: "UK Ayrton Fund",
    funder: "UK Foreign, Commonwealth & Development Office",
    awardRange: "£1M–£10M",
    eligibilitySummary:
      "Transformative clean energy innovations for the poorest countries. Focus on off-grid energy access and energy efficiency for underserved communities.",
    focusAreas: ["Climate", "Agriculture", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.gov.uk/guidance/ayrton-fund",
    submissionType: "portal",
    portalLabel: "Apply at gov.uk/guidance/ayrton-fund",
  },
  {
    id: "fao-innovation",
    name: "FAO Innovation Grant",
    funder: "Food and Agriculture Organization of the United Nations",
    awardRange: "$50K–$500K",
    eligibilitySummary:
      "Innovations addressing food security, sustainable agriculture, and rural livelihoods in FAO member countries. Open to NGOs and social enterprises.",
    focusAreas: ["Agriculture", "Climate", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.fao.org/partnerships/resource-mobilization/en",
    submissionType: "portal",
    portalLabel: "Apply at fao.org",
  },
  {
    id: "ifad-rural-innovation",
    name: "IFAD Rural Innovation Fund",
    funder: "International Fund for Agricultural Development",
    awardRange: "$100K–$2M",
    eligibilitySummary:
      "Rural smallholder-focused innovations in agriculture, finance, and market access for low-income countries. Open to NGOs, cooperatives, and social enterprises.",
    focusAreas: ["Agriculture", "Financial Inclusion", "Climate"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.ifad.org/en/innovation",
    submissionType: "portal",
    portalLabel: "Apply at ifad.org",
  },

  // ── Africa-Specific ──────────────────────────────────────────────────────────
  {
    id: "tony-elumelu-foundation",
    name: "Tony Elumelu Foundation Entrepreneurship Programme",
    funder: "Tony Elumelu Foundation",
    awardRange: "$5K seed capital + mentorship",
    eligibilitySummary:
      "African entrepreneurs with viable early-stage business ideas. $5,000 non-refundable seed capital plus 12 weeks of training and mentorship.",
    focusAreas: ["Healthcare", "Agriculture", "Financial Inclusion", "Education", "Other"],
    geographies: ["Sub-Saharan Africa"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://www.tonyelumelufoundation.org/teep",
    submissionType: "portal",
    portalLabel: "Apply at tonyelumelufoundation.org",
  },
  {
    id: "mastercard-foundation",
    name: "Mastercard Foundation Scholars Program",
    funder: "Mastercard Foundation",
    awardRange: "Varies by partner institution",
    eligibilitySummary:
      "Talented young Africans from disadvantaged backgrounds pursuing tertiary education and leadership development. Partners with leading African universities.",
    focusAreas: ["Education", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa"],
    stages: ["Nonprofit"],
    requiresNonprofit: true,
    url: "https://mastercardfdn.org/all/scholars",
    submissionType: "portal",
    portalLabel: "Apply at mastercardfdn.org",
  },
  {
    id: "mo-ibrahim-foundation",
    name: "Mo Ibrahim Foundation Governance Grants",
    funder: "Mo Ibrahim Foundation",
    awardRange: "$200K–$500K",
    eligibilitySummary:
      "African civil society organizations and researchers advancing governance, leadership, and accountability across the continent.",
    focusAreas: ["Education", "Other"],
    geographies: ["Sub-Saharan Africa"],
    stages: ["Nonprofit"],
    requiresNonprofit: true,
    url: "https://mo.ibrahim.foundation/foundation/partnerships-grants",
    submissionType: "portal",
    portalLabel: "Apply at mo.ibrahim.foundation",
  },
  {
    id: "african-development-foundation",
    name: "African Development Foundation Grants",
    funder: "US African Development Foundation",
    awardRange: "Up to $250K",
    eligibilitySummary:
      "African-led businesses and cooperatives that create economic opportunities for underserved communities in sub-Saharan Africa.",
    focusAreas: ["Agriculture", "Financial Inclusion", "Healthcare", "Other"],
    geographies: ["Sub-Saharan Africa"],
    stages: ["Pre-seed", "Seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.usadf.gov/apply",
    submissionType: "portal",
    portalLabel: "Apply at usadf.gov",
  },
  {
    id: "jack-ma-netpreneur-prize",
    name: "Jack Ma Foundation Africa Netpreneur Prize",
    funder: "Jack Ma Foundation",
    awardRange: "$1M total (10 winners)",
    eligibilitySummary:
      "African entrepreneurs with profitable or near-profitable businesses demonstrating innovation and social impact. Open to businesses operating in Africa.",
    focusAreas: ["Financial Inclusion", "Agriculture", "Healthcare", "Education", "Other"],
    geographies: ["Sub-Saharan Africa"],
    stages: ["Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://afrinnovator.com",
    submissionType: "portal",
    portalLabel: "Apply at afrinnovator.com",
  },
  {
    id: "gsma-innovation-fund",
    name: "GSMA Innovation Fund",
    funder: "GSMA",
    awardRange: "$100K–$250K",
    eligibilitySummary:
      "Mobile-enabled innovations in agriculture, health, financial services, and utilities serving underserved populations in low- and middle-income countries.",
    focusAreas: ["Healthcare", "Agriculture", "Financial Inclusion", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia"],
    stages: ["Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://www.gsma.com/mobilefordevelopment/gsma-innovation-fund",
    submissionType: "portal",
    portalLabel: "Apply at gsma.com/mobilefordevelopment",
  },
  {
    id: "norrsken-africa",
    name: "Norrsken22 Africa Fund",
    funder: "Norrsken Foundation",
    awardRange: "$100K–$1M equity investment",
    eligibilitySummary:
      "Africa-based tech startups with measurable social impact and commercial viability. Focus on climate, health, education, and financial services.",
    focusAreas: ["Healthcare", "Climate", "Education", "Financial Inclusion"],
    geographies: ["Sub-Saharan Africa"],
    stages: ["Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://www.norrsken22.com",
    submissionType: "portal",
    portalLabel: "Apply at norrsken22.com",
  },
  {
    id: "mest-africa",
    name: "MEST Africa Fellowship & Fund",
    funder: "MEST Africa",
    awardRange: "Stipend + up to $150K seed equity",
    eligibilitySummary:
      "Tech entrepreneurs in Africa selected for training program and seed investment. Focus on scalable technology businesses with pan-African potential.",
    focusAreas: ["Healthcare", "Agriculture", "Financial Inclusion", "Education", "Other"],
    geographies: ["Sub-Saharan Africa"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://meltwater.org/mest-fellowship",
    submissionType: "portal",
    portalLabel: "Apply at meltwater.org/mest-fellowship",
  },
  {
    id: "cchub-growth-capital",
    name: "CcHUB Growth Capital",
    funder: "Co-creation Hub (CcHUB)",
    awardRange: "$25K–$500K",
    eligibilitySummary:
      "African tech startups at seed to early growth stage solving local problems with technology. CcHUB operates accelerator programs across West and East Africa.",
    focusAreas: ["Healthcare", "Education", "Agriculture", "Financial Inclusion", "Other"],
    geographies: ["Sub-Saharan Africa"],
    stages: ["Pre-seed", "Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://cchubnigeria.com/growth-capital",
    submissionType: "portal",
    portalLabel: "Apply at cchubnigeria.com",
  },

  // ── Global Health ────────────────────────────────────────────────────────────
  {
    id: "nih-fogarty",
    name: "NIH Fogarty International Center Grants",
    funder: "National Institutes of Health — Fogarty International Center",
    awardRange: "$100K–$500K",
    eligibilitySummary:
      "Global health research and training programs in LMICs. US institutions partnering with overseas institutions to build research capacity.",
    focusAreas: ["Healthcare", "Education"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.fic.nih.gov/Funding/Pages/default.aspx",
    submissionType: "portal",
    portalLabel: "Apply via Grants.gov",
  },
  {
    id: "cdc-foundation",
    name: "CDC Foundation Grants",
    funder: "CDC Foundation",
    awardRange: "$50K–$2M",
    eligibilitySummary:
      "Public health innovations strengthening disease prevention and health protection globally. Preference for evidence-based interventions.",
    focusAreas: ["Healthcare"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.cdcfoundation.org/partner-with-us",
    submissionType: "portal",
    portalLabel: "Apply at cdcfoundation.org",
  },
  {
    id: "gavi-innovation",
    name: "Gavi Innovation Grants",
    funder: "Gavi, the Vaccine Alliance",
    awardRange: "$500K–$5M",
    eligibilitySummary:
      "Innovations improving vaccine access, delivery, and immunization systems in 57 lower-income countries. Open to manufacturers, NGOs, and tech companies.",
    focusAreas: ["Healthcare"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.gavi.org/programmes-impact/programmatic-partnerships",
    submissionType: "portal",
    portalLabel: "Apply at gavi.org",
  },
  {
    id: "global-fund-grants",
    name: "The Global Fund Grants",
    funder: "The Global Fund to Fight AIDS, Tuberculosis and Malaria",
    awardRange: "$1M–$50M",
    eligibilitySummary:
      "National programs and NGOs implementing HIV, TB, and malaria programs in high-burden countries. Applications submitted through Country Coordinating Mechanisms.",
    focusAreas: ["Healthcare"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.theglobalfund.org/en/applying-for-funding",
    submissionType: "portal",
    portalLabel: "Apply at theglobalfund.org",
  },
  {
    id: "merck-for-mothers",
    name: "Merck for Mothers Grants",
    funder: "Merck",
    awardRange: "$250K–$1M",
    eligibilitySummary:
      "Innovations improving maternal health outcomes in LMICs and underserved US communities. Focus on preventing preventable maternal deaths.",
    focusAreas: ["Healthcare"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Latin America", "United States"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.merckformothers.com/apply",
    submissionType: "portal",
    portalLabel: "Apply at merckformothers.com",
  },
  {
    id: "jj-innovation",
    name: "Johnson & Johnson Innovation Funding",
    funder: "Johnson & Johnson",
    awardRange: "$50K–$500K",
    eligibilitySummary:
      "Early-stage health innovations in pharmaceuticals, medtech, and consumer health. Global JLABS network provides access to funding and resources.",
    focusAreas: ["Healthcare"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Pre-seed", "Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://jnjinnovation.com",
    submissionType: "portal",
    portalLabel: "Apply at jnjinnovation.com",
  },
  {
    id: "pfizer-global-medical-grants",
    name: "Pfizer Global Medical Grants",
    funder: "Pfizer",
    awardRange: "$25K–$500K",
    eligibilitySummary:
      "Independent educational and quality improvement initiatives in Pfizer therapeutic areas. Open to academic institutions, hospitals, and nonprofits.",
    focusAreas: ["Healthcare", "Education"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://grantsandgiving.pfizer.com",
    submissionType: "portal",
    portalLabel: "Apply at grantsandgiving.pfizer.com",
  },
  {
    id: "bms-foundation",
    name: "Bristol Myers Squibb Foundation Grants",
    funder: "Bristol Myers Squibb Foundation",
    awardRange: "$50K–$1M",
    eligibilitySummary:
      "Programs improving cancer care and health equity in underserved communities, including sub-Saharan Africa. Open to nonprofits and health institutions.",
    focusAreas: ["Healthcare"],
    geographies: ["Sub-Saharan Africa", "Latin America", "United States"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.bms.com/about/responsibility/bristol-myers-squibb-foundation.html",
    submissionType: "portal",
    portalLabel: "Apply at bms.com/foundation",
  },

  // ── Climate / Environment ─────────────────────────────────────────────────────
  {
    id: "bezos-earth-fund",
    name: "Bezos Earth Fund",
    funder: "Bezos Earth Fund",
    awardRange: "$1M–$100M",
    eligibilitySummary:
      "Bold, large-scale climate and nature solutions accelerating the transition to a sustainable future. Open to nonprofits, research institutions, and social enterprises.",
    focusAreas: ["Climate", "Agriculture"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.bezosearthfund.org/grants",
    submissionType: "portal",
    portalLabel: "Apply at bezosearthfund.org",
  },
  {
    id: "climateworks-foundation",
    name: "ClimateWorks Foundation Grants",
    funder: "ClimateWorks Foundation",
    awardRange: "$200K–$3M",
    eligibilitySummary:
      "Climate mitigation initiatives advancing clean energy, sustainable land use, and industrial decarbonization globally. Primarily focused on nonprofits.",
    focusAreas: ["Climate", "Agriculture"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.climateworks.org/grants-and-partners",
    submissionType: "portal",
    portalLabel: "Apply at climateworks.org",
  },
  {
    id: "bloomberg-philanthropies",
    name: "Bloomberg Philanthropies Environment Program",
    funder: "Bloomberg Philanthropies",
    awardRange: "$500K–$10M",
    eligibilitySummary:
      "Initiatives fighting climate change and protecting public health through clean energy, ocean conservation, and city-level climate action.",
    focusAreas: ["Climate", "Healthcare", "Other"],
    geographies: ["Sub-Saharan Africa", "Southeast Asia", "Latin America", "United States", "Global"],
    stages: ["Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.bloomberg.org/environment",
    submissionType: "invitation",
    portalLabel: "Invite-only; express interest at bloomberg.org",
  },
  {
    id: "grantham-foundation",
    name: "Grantham Foundation for the Protection of the Environment",
    funder: "Grantham Foundation",
    awardRange: "$100K–$2M",
    eligibilitySummary:
      "Environmental organizations protecting biodiversity and fighting climate change through research, advocacy, and on-the-ground action.",
    focusAreas: ["Climate", "Agriculture"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.granthamfoundation.org/apply",
    submissionType: "portal",
    portalLabel: "Apply at granthamfoundation.org",
  },
  {
    id: "energy-foundation",
    name: "Energy Foundation Grants",
    funder: "Energy Foundation",
    awardRange: "$100K–$1M",
    eligibilitySummary:
      "Clean energy policy, research, and deployment programs advancing the transition away from fossil fuels. Primarily supports US-based advocacy and China programs.",
    focusAreas: ["Climate"],
    geographies: ["United States", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.ef.org/grants",
    submissionType: "portal",
    portalLabel: "Apply at ef.org",
  },
  {
    id: "ikea-foundation",
    name: "IKEA Foundation Grants",
    funder: "IKEA Foundation",
    awardRange: "€1M–€10M",
    eligibilitySummary:
      "Large-scale programs addressing climate change and children's rights in countries where IKEA Foundation operates. Primarily works with established NGO partners.",
    focusAreas: ["Climate", "Education", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia"],
    stages: ["Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://ikeafoundation.org/apply",
    submissionType: "portal",
    portalLabel: "Apply at ikeafoundation.org",
  },
  {
    id: "children-investment-fund",
    name: "Children's Investment Fund Foundation",
    funder: "Children's Investment Fund Foundation",
    awardRange: "$500K–$10M",
    eligibilitySummary:
      "Programs improving child health, nutrition, and climate resilience in sub-Saharan Africa and South Asia. Focus on systemic change at scale.",
    focusAreas: ["Healthcare", "Climate", "Agriculture", "Education"],
    geographies: ["Sub-Saharan Africa", "South Asia"],
    stages: ["Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://ciff.org/grant-portfolio",
    submissionType: "invitation",
    portalLabel: "Submit expression of interest at ciff.org",
  },

  // ── Tech / AI ────────────────────────────────────────────────────────────────
  {
    id: "microsoft-ai-for-good",
    name: "Microsoft AI for Good",
    funder: "Microsoft",
    awardRange: "Up to $2M in Azure credits + cash grants",
    eligibilitySummary:
      "Nonprofits and researchers applying AI to humanitarian challenges in health, environment, accessibility, and cultural heritage.",
    focusAreas: ["Healthcare", "Climate", "Agriculture", "Education", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.microsoft.com/en-us/ai/ai-for-good",
    submissionType: "portal",
    portalLabel: "Apply at microsoft.com/ai/ai-for-good",
  },
  {
    id: "salesforce-org",
    name: "Salesforce.org Grants",
    funder: "Salesforce.org",
    awardRange: "$10K–$100K + product donations",
    eligibilitySummary:
      "Nonprofits and educational institutions using technology to create a more equitable world. Includes product grants (Salesforce licenses) and cash grants.",
    focusAreas: ["Education", "Healthcare", "Financial Inclusion", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.salesforce.org/grants",
    submissionType: "portal",
    portalLabel: "Apply at salesforce.org/grants",
  },
  {
    id: "schmidt-futures",
    name: "Schmidt Futures Innovation Fellows",
    funder: "Schmidt Futures",
    awardRange: "$100K–$5M",
    eligibilitySummary:
      "Scientists, engineers, and entrepreneurs applying rigorous approaches to important problems. Emphasis on scientific talent and novel solutions.",
    focusAreas: ["Healthcare", "Climate", "Education", "Other"],
    geographies: ["Global"],
    stages: ["Pre-seed", "Seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.schmidtfutures.com/our-work/grants",
    submissionType: "portal",
    portalLabel: "Apply at schmidtfutures.com",
  },
  {
    id: "open-philanthropy",
    name: "Open Philanthropy Grants",
    funder: "Open Philanthropy",
    awardRange: "$100K–$10M+",
    eligibilitySummary:
      "High-impact work in global health, animal welfare, AI safety, and scientific research. Focus on neglected cause areas with high expected value.",
    focusAreas: ["Healthcare", "Agriculture", "Education", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.openphilanthropy.org/apply-for-funding",
    submissionType: "portal",
    portalLabel: "Apply at openphilanthropy.org",
  },

  // ── Social Entrepreneurship ───────────────────────────────────────────────────
  {
    id: "ashoka-fellowship",
    name: "Ashoka Fellowship",
    funder: "Ashoka",
    awardRange: "Stipend (varies by country) + lifetime support",
    eligibilitySummary:
      "Systems-changing social innovators with a pattern-changing idea and entrepreneurial quality. Elected by invitation after rigorous selection process.",
    focusAreas: ["Healthcare", "Education", "Agriculture", "Financial Inclusion", "Climate", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.ashoka.org/en-US/program/ashoka-fellows",
    submissionType: "invitation",
    portalLabel: "Nominate at ashoka.org",
  },
  {
    id: "acumen-fellowship",
    name: "Acumen Fellowship",
    funder: "Acumen",
    awardRange: "Fellowship stipend + network access",
    eligibilitySummary:
      "Emerging leaders working on market-based solutions to poverty in Africa, South Asia, and Latin America. Fellows selected through competitive process.",
    focusAreas: ["Healthcare", "Agriculture", "Financial Inclusion", "Education", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Latin America"],
    stages: ["Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://acumen.org/fellowships",
    submissionType: "portal",
    portalLabel: "Apply at acumen.org/fellowships",
  },
  {
    id: "village-capital",
    name: "Village Capital Programs",
    funder: "Village Capital",
    awardRange: "$50K–$200K investment",
    eligibilitySummary:
      "Early-stage startups addressing real-world problems in agriculture, education, financial inclusion, and health in underserved markets.",
    focusAreas: ["Agriculture", "Education", "Financial Inclusion", "Healthcare"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America"],
    stages: ["Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://vilcap.com/programs",
    submissionType: "portal",
    portalLabel: "Apply at vilcap.com",
  },
  {
    id: "schwab-foundation",
    name: "Schwab Foundation Social Entrepreneur Award",
    funder: "Schwab Foundation for Social Entrepreneurship",
    awardRange: "Recognition + WEF platform (no cash award)",
    eligibilitySummary:
      "Established social entrepreneurs with proven impact at scale. Awardees gain access to World Economic Forum platform and global network.",
    focusAreas: ["Healthcare", "Education", "Agriculture", "Financial Inclusion", "Climate", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.schwabfound.org/apply",
    submissionType: "portal",
    portalLabel: "Apply at schwabfound.org",
  },
  {
    id: "draper-richards-kaplan",
    name: "Draper Richards Kaplan Foundation",
    funder: "Draper Richards Kaplan Foundation",
    awardRange: "$300K over 3 years",
    eligibilitySummary:
      "Early-stage, high-impact nonprofits addressing significant social issues with innovative approaches. Must be 501(c)(3) in first 3 years of operation.",
    focusAreas: ["Healthcare", "Education", "Financial Inclusion", "Climate", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Latin America", "United States", "Global"],
    stages: ["Pre-seed", "Seed", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.drkfoundation.org/apply",
    submissionType: "portal",
    portalLabel: "Apply at drkfoundation.org",
  },

  // ── Education ────────────────────────────────────────────────────────────────
  {
    id: "lumina-foundation",
    name: "Lumina Foundation Grants",
    funder: "Lumina Foundation",
    awardRange: "$100K–$2M",
    eligibilitySummary:
      "Organizations expanding postsecondary education access and attainment, particularly for adult learners and underrepresented students in the US.",
    focusAreas: ["Education"],
    geographies: ["United States"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.luminafoundation.org/funding",
    submissionType: "portal",
    portalLabel: "Apply at luminafoundation.org",
  },
  {
    id: "hewlett-foundation-education",
    name: "William & Flora Hewlett Foundation — Education Program",
    funder: "William and Flora Hewlett Foundation",
    awardRange: "$100K–$3M",
    eligibilitySummary:
      "Initiatives improving US K-12 education quality and expanding open educational resources globally. Emphasis on deeper learning and education equity.",
    focusAreas: ["Education"],
    geographies: ["Sub-Saharan Africa", "South Asia", "United States", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://hewlett.org/grants",
    submissionType: "portal",
    portalLabel: "Apply at hewlett.org/grants",
  },

  // ── Financial Inclusion ──────────────────────────────────────────────────────
  {
    id: "grameen-foundation",
    name: "Grameen Foundation Grants",
    funder: "Grameen Foundation",
    awardRange: "$50K–$1M",
    eligibilitySummary:
      "Organizations using digital finance and technology to expand economic opportunity for people living in poverty, particularly women.",
    focusAreas: ["Financial Inclusion", "Agriculture", "Healthcare"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://grameenfoundation.org/what-we-do/approach",
    submissionType: "portal",
    portalLabel: "Apply at grameenfoundation.org",
  },
  {
    id: "citi-foundation",
    name: "Citi Foundation Grants",
    funder: "Citi Foundation",
    awardRange: "$100K–$1M",
    eligibilitySummary:
      "Organizations advancing economic progress and improving financial health for low-income people in cities. Focus on youth employment and financial inclusion.",
    focusAreas: ["Financial Inclusion", "Education"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "United States"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.citigroup.com/global/foundation",
    submissionType: "portal",
    portalLabel: "Apply at citigroup.com/foundation",
  },
  {
    id: "visa-foundation",
    name: "Visa Foundation Grants",
    funder: "Visa Foundation",
    awardRange: "$100K–$2M",
    eligibilitySummary:
      "Organizations supporting small and micro businesses and advancing inclusive economies, with a focus on women entrepreneurs in emerging markets.",
    focusAreas: ["Financial Inclusion", "Education"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://usa.visa.com/about-visa/visa-foundation.html",
    submissionType: "portal",
    portalLabel: "Apply at usa.visa.com/visa-foundation",
  },
  {
    id: "metlife-foundation",
    name: "MetLife Foundation Grants",
    funder: "MetLife Foundation",
    awardRange: "$100K–$500K",
    eligibilitySummary:
      "Financial health programs for low- and moderate-income individuals, with emphasis on savings, insurance access, and financial resilience.",
    focusAreas: ["Financial Inclusion", "Education"],
    geographies: ["Sub-Saharan Africa", "Latin America", "United States", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.metlife.com/metlife-foundation",
    submissionType: "portal",
    portalLabel: "Apply at metlife.com/metlife-foundation",
  },
  {
    id: "jpmorgan-chase-foundation",
    name: "JPMorgan Chase Foundation Grants",
    funder: "JPMorgan Chase Foundation",
    awardRange: "$100K–$5M",
    eligibilitySummary:
      "Workforce development, financial health, small business growth, and community development programs in cities where JPMorgan Chase operates.",
    focusAreas: ["Financial Inclusion", "Education", "Other"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Latin America", "United States", "Global"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://www.jpmorganchase.com/impact/philanthropy",
    submissionType: "portal",
    portalLabel: "Apply at jpmorganchase.com/impact",
  },

  // ── Arts & Culture ───────────────────────────────────────────────────────────
  {
    id: "nea-grants",
    name: "National Endowment for the Arts Grants",
    funder: "National Endowment for the Arts",
    awardRange: "$10K–$100K",
    eligibilitySummary:
      "US nonprofit arts organizations, arts education programs, and individual artists (via state arts agencies) across all disciplines including music, theater, visual arts, and literature.",
    focusAreas: ["Arts & Culture", "Education"],
    geographies: ["United States"],
    stages: ["Individual / Solo", "Nonprofit", "Established Business"],
    requiresNonprofit: false,
    url: "https://www.arts.gov/grants",
    submissionType: "portal",
    portalLabel: "Apply at arts.gov/grants",
  },
  {
    id: "neh-grants",
    name: "National Endowment for the Humanities Grants",
    funder: "National Endowment for the Humanities",
    awardRange: "$25K–$500K",
    eligibilitySummary:
      "US-based institutions and individuals pursuing humanities research, education, preservation, and public programs. Includes fellowships, preservation grants, and institutional awards.",
    focusAreas: ["Arts & Culture", "Education", "Research & Science"],
    geographies: ["United States"],
    stages: ["Individual / Solo", "Nonprofit", "Pre-seed"],
    requiresNonprofit: false,
    url: "https://www.neh.gov/grants",
    submissionType: "portal",
    portalLabel: "Apply at neh.gov/grants",
  },
  {
    id: "sundance-documentary-fund",
    name: "Sundance Institute Documentary Fund",
    funder: "Sundance Institute",
    awardRange: "$20K–$50K",
    eligibilitySummary:
      "Independent documentary filmmakers worldwide at any stage of production. Supports films that explore pressing social, cultural, and political issues with a distinct cinematic vision.",
    focusAreas: ["Arts & Culture", "Media & Journalism"],
    geographies: ["Global"],
    stages: ["Individual / Solo", "Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://www.sundance.org/programs/documentary-fund",
    submissionType: "portal",
    portalLabel: "Apply at sundance.org/programs/documentary-fund",
  },
  {
    id: "tribeca-film-institute",
    name: "Tribeca Film Institute Grants",
    funder: "Tribeca Film Institute",
    awardRange: "$10K–$75K",
    eligibilitySummary:
      "Independent filmmakers and storytellers with narratives underrepresented in mainstream media. Supports documentary, narrative fiction, and interactive media projects.",
    focusAreas: ["Arts & Culture", "Media & Journalism"],
    geographies: ["Global"],
    stages: ["Individual / Solo", "Pre-seed", "Seed"],
    requiresNonprofit: false,
    url: "https://www.tribecafilm.com/institute",
    submissionType: "portal",
    portalLabel: "Apply at tribecafilm.com/institute",
  },
  {
    id: "creative-capital-foundation",
    name: "Creative Capital Foundation Awards",
    funder: "Creative Capital Foundation",
    awardRange: "Up to $50K per project",
    eligibilitySummary:
      "US-based individual artists working in performing arts, visual arts, film/video, and emerging fields. Provides multi-year financial and advisory support for ambitious projects.",
    focusAreas: ["Arts & Culture"],
    geographies: ["United States"],
    stages: ["Individual / Solo"],
    requiresNonprofit: false,
    url: "https://creative-capital.org/apply",
    submissionType: "portal",
    portalLabel: "Apply at creative-capital.org/apply",
  },
  {
    id: "guggenheim-fellowship",
    name: "Guggenheim Fellowship",
    funder: "John Simon Guggenheim Memorial Foundation",
    awardRange: "$40K–$90K",
    eligibilitySummary:
      "Mid-career scholars, artists, and scientists in the US and Canada who have demonstrated exceptional capacity for productive scholarship or exceptional creative ability. Covers all disciplines.",
    focusAreas: ["Arts & Culture", "Research & Science"],
    geographies: ["United States"],
    stages: ["Individual / Solo"],
    requiresNonprofit: false,
    url: "https://www.gf.org/applicants",
    submissionType: "portal",
    portalLabel: "Apply at gf.org/applicants",
  },
  {
    id: "knight-arts-challenge",
    name: "Knight Foundation Arts Challenge",
    funder: "John S. and James L. Knight Foundation",
    awardRange: "$5K–$1M",
    eligibilitySummary:
      "Artists and arts organizations with the best ideas for engaging communities in Knight's 26 US cities through the arts. Open to individuals, nonprofits, and for-profits.",
    focusAreas: ["Arts & Culture"],
    geographies: ["United States"],
    stages: ["Individual / Solo", "Pre-seed", "Seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://knightfoundation.org/programs/arts",
    submissionType: "portal",
    portalLabel: "Apply at knightfoundation.org/programs/arts",
  },
  {
    id: "map-fund",
    name: "MAP Fund",
    funder: "MAP Fund",
    awardRange: "$15K–$45K",
    eligibilitySummary:
      "US-based performing artists and ensembles developing original live performance works that challenge aesthetic and social norms. Prioritizes artists from historically underserved communities.",
    focusAreas: ["Arts & Culture"],
    geographies: ["United States"],
    stages: ["Individual / Solo", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://mapfund.org/apply",
    submissionType: "portal",
    portalLabel: "Apply at mapfund.org/apply",
  },

  // ── Small Business / Entrepreneurship ────────────────────────────────────────
  {
    id: "sba-sbir-general",
    name: "SBA Small Business Innovation Research (SBIR)",
    funder: "US Small Business Administration",
    awardRange: "$275K (Phase I) – $1.83M (Phase II)",
    eligibilitySummary:
      "US-based small businesses with fewer than 500 employees pursuing R&D in federal agency priority areas across 11 participating agencies. Must be majority US-owned and operated.",
    focusAreas: ["Technology & AI", "Research & Science", "Other"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://www.sbir.gov",
    submissionType: "portal",
    portalLabel: "Apply at sbir.gov",
  },
  {
    id: "usda-rural-business-development",
    name: "USDA Rural Business Development Grant",
    funder: "US Department of Agriculture",
    awardRange: "$10K–$500K",
    eligibilitySummary:
      "US nonprofits, public agencies, and federally recognized tribes supporting small and emerging rural businesses in communities with populations under 50,000.",
    focusAreas: ["Agriculture & Food", "Financial Inclusion", "Other"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.rd.usda.gov/programs-services/business-programs/rural-business-development-grants",
    submissionType: "portal",
    portalLabel: "Apply via Grants.gov",
  },
  {
    id: "amber-grant-women",
    name: "Amber Grant for Women",
    funder: "WomensNet",
    awardRange: "$10K monthly + $25K annual",
    eligibilitySummary:
      "Women-owned businesses at any stage in the US. Monthly $10,000 grants with an additional $25,000 year-end grant awarded to one monthly recipient. No minimum revenue requirement.",
    focusAreas: ["Other", "Financial Inclusion"],
    geographies: ["United States"],
    stages: ["Individual / Solo", "Pre-seed", "Seed", "Established Business"],
    requiresNonprofit: false,
    url: "https://ambergrant.com",
    submissionType: "portal",
    portalLabel: "Apply at ambergrant.com",
  },
  {
    id: "ifundwomen-grants",
    name: "IFundWomen Grants",
    funder: "IFundWomen",
    awardRange: "$5K–$50K",
    eligibilitySummary:
      "Women-owned and non-binary-owned small businesses and startups in the US. Platform offers brand-sponsored grants across industries including food, wellness, and tech.",
    focusAreas: ["Other", "Financial Inclusion"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Established Business"],
    requiresNonprofit: false,
    url: "https://ifundwomen.com/grants",
    submissionType: "portal",
    portalLabel: "Apply at ifundwomen.com/grants",
  },
  {
    id: "tory-burch-foundation-fellows",
    name: "Tory Burch Foundation Fellows Program",
    funder: "Tory Burch Foundation",
    awardRange: "$5K + resources",
    eligibilitySummary:
      "Women entrepreneurs in the US running established businesses with at least $75K in annual revenue or $150K raised. Provides business education, mentoring, and community.",
    focusAreas: ["Financial Inclusion", "Other"],
    geographies: ["United States"],
    stages: ["Seed", "Series A", "Established Business"],
    requiresNonprofit: false,
    url: "https://www.toryburchfoundation.org/programs/fellows",
    submissionType: "portal",
    portalLabel: "Apply at toryburchfoundation.org/programs/fellows",
  },
  {
    id: "hello-alice-small-business-grants",
    name: "Hello Alice Small Business Grants",
    funder: "Hello Alice",
    awardRange: "$10K–$50K",
    eligibilitySummary:
      "Small business owners across the US, with rotating sponsored grant programs targeting underrepresented founders including women, BIPOC, veterans, and LGBTQ+ entrepreneurs.",
    focusAreas: ["Financial Inclusion", "Other"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Established Business"],
    requiresNonprofit: false,
    url: "https://helloalice.com/grants",
    submissionType: "portal",
    portalLabel: "Apply at helloalice.com/grants",
  },
  {
    id: "fearless-fund",
    name: "Fearless Fund Grants & Investment",
    funder: "Fearless Fund",
    awardRange: "$20K grants; $100K–$1M investment",
    eligibilitySummary:
      "Women of color founders with US-based businesses at pre-seed through Series A. Grant programs include the Strivers Grant for pre-revenue concepts and the Fearless Strivers Grant.",
    focusAreas: ["Financial Inclusion", "Other"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://fearlessfund.com",
    submissionType: "portal",
    portalLabel: "Apply at fearlessfund.com",
  },

  // ── Research & Science ───────────────────────────────────────────────────────
  {
    id: "nsf-career-award",
    name: "NSF CAREER Award",
    funder: "National Science Foundation",
    awardRange: "~$500K over 5 years",
    eligibilitySummary:
      "Early-career US faculty at tenure-track positions who have not previously received a CAREER award. Supports research and education plans that build a foundation for a lifetime of scientific leadership.",
    focusAreas: ["Research & Science", "Education", "Technology & AI"],
    geographies: ["United States"],
    stages: ["Individual / Solo"],
    requiresNonprofit: false,
    url: "https://www.nsf.gov/funding/pgm_summ.jsp?pims_id=503214",
    submissionType: "portal",
    portalLabel: "Apply via Research.gov",
  },
  {
    id: "nih-r01",
    name: "NIH R01 Research Project Grant",
    funder: "National Institutes of Health",
    awardRange: "Up to $500K direct costs/year",
    eligibilitySummary:
      "Investigators at US or international institutions conducting independent health-related research with a defined hypothesis. The flagship NIH grant mechanism for established and emerging researchers.",
    focusAreas: ["Research & Science", "Healthcare"],
    geographies: ["United States", "Global"],
    stages: ["Individual / Solo", "Nonprofit", "Established Business"],
    requiresNonprofit: false,
    url: "https://grants.nih.gov/grants/funding/r01.htm",
    submissionType: "portal",
    portalLabel: "Apply via Grants.gov",
  },
  {
    id: "fulbright-scholar",
    name: "Fulbright Scholar Program",
    funder: "US Department of State / Council for International Exchange of Scholars",
    awardRange: "Stipend, travel, and housing allowance (varies by country)",
    eligibilitySummary:
      "US citizens who are faculty, administrators, researchers, artists, journalists, and professionals seeking to lecture, research, or conduct arts projects abroad for 2–9 months.",
    focusAreas: ["Research & Science", "Arts & Culture", "Education"],
    geographies: ["Global"],
    stages: ["Individual / Solo"],
    requiresNonprofit: false,
    url: "https://cies.org/us-scholar-program",
    submissionType: "portal",
    portalLabel: "Apply at cies.org",
  },
  {
    id: "hhmi-investigator",
    name: "HHMI Investigator Program",
    funder: "Howard Hughes Medical Institute",
    awardRange: "~$1.5M–$2M over 5 years",
    eligibilitySummary:
      "Outstanding biomedical scientists at eligible US research institutions who are faculty pursuing creative, ambitious research. Nomination by institution required; invitation-based selection.",
    focusAreas: ["Research & Science", "Healthcare"],
    geographies: ["United States"],
    stages: ["Individual / Solo"],
    requiresNonprofit: false,
    url: "https://www.hhmi.org/programs/investigators",
    submissionType: "invitation",
    portalLabel: "Nominated by institution; see hhmi.org/programs/investigators",
  },
  {
    id: "kavli-foundation",
    name: "Kavli Foundation Grants",
    funder: "The Kavli Foundation",
    awardRange: "$500K–$10M",
    eligibilitySummary:
      "Research institutions and scientists in astrophysics, nanoscience, neuroscience, and theoretical physics. Primarily funds through endowed institutes; some open grant programs for collaborative research.",
    focusAreas: ["Research & Science"],
    geographies: ["United States", "Global"],
    stages: ["Individual / Solo", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://kavlifoundation.org/grants",
    submissionType: "portal",
    portalLabel: "Apply at kavlifoundation.org/grants",
  },
  {
    id: "simons-foundation",
    name: "Simons Foundation Grants",
    funder: "Simons Foundation",
    awardRange: "$100K–$5M+",
    eligibilitySummary:
      "Researchers in mathematics, theoretical physics, life sciences, and autism research at universities and research institutes. Includes investigator awards, collaboration grants, and targeted programs.",
    focusAreas: ["Research & Science", "Healthcare"],
    geographies: ["United States", "Global"],
    stages: ["Individual / Solo", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.simonsfoundation.org/funding-opportunities",
    submissionType: "portal",
    portalLabel: "Apply at simonsfoundation.org/funding-opportunities",
  },
  {
    id: "darpa-young-faculty",
    name: "DARPA Young Faculty Award",
    funder: "Defense Advanced Research Projects Agency",
    awardRange: "$500K over 2 years",
    eligibilitySummary:
      "Early-career US faculty (within 7 years of their first faculty appointment) with research in areas of importance to national security including AI, biotech, microelectronics, and quantum. Must be at accredited US institution.",
    focusAreas: ["Research & Science", "Technology & AI"],
    geographies: ["United States"],
    stages: ["Individual / Solo"],
    requiresNonprofit: false,
    url: "https://www.darpa.mil/work-with-us/for-universities/young-faculty-award",
    submissionType: "portal",
    portalLabel: "Apply at darpa.mil/work-with-us",
  },

  // ── Journalism & Media ───────────────────────────────────────────────────────
  {
    id: "pulitzer-center-crisis-reporting",
    name: "Pulitzer Center on Crisis Reporting Grants",
    funder: "Pulitzer Center on Crisis Reporting",
    awardRange: "$5K–$50K",
    eligibilitySummary:
      "Journalists and media organizations worldwide producing in-depth reporting on underreported global crises. Projects must have clear distribution partners and a focus on systemic issues.",
    focusAreas: ["Media & Journalism", "Arts & Culture"],
    geographies: ["Sub-Saharan Africa", "South Asia", "Southeast Asia", "Latin America", "Global"],
    stages: ["Individual / Solo", "Pre-seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://pulitzercenter.org/grants-fellowships",
    submissionType: "portal",
    portalLabel: "Apply at pulitzercenter.org/grants-fellowships",
  },
  {
    id: "ire-grants",
    name: "IRE Investigative Journalism Grants",
    funder: "Investigative Reporters and Editors",
    awardRange: "$1K–$25K",
    eligibilitySummary:
      "Journalists and newsrooms conducting investigative or data-driven reporting projects. Includes the IRE Fund and specialized fellowships for reporters from underrepresented communities.",
    focusAreas: ["Media & Journalism"],
    geographies: ["United States", "Global"],
    stages: ["Individual / Solo", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.ire.org/training/fellowships-and-awards",
    submissionType: "portal",
    portalLabel: "Apply at ire.org/training/fellowships-and-awards",
  },
  {
    id: "national-geographic-grants",
    name: "National Geographic Society Grants",
    funder: "National Geographic Society",
    awardRange: "$5K–$50K",
    eligibilitySummary:
      "Explorers, scientists, photographers, journalists, and storytellers undertaking field projects in conservation, science, storytelling, and education that inspire a connection to our planet.",
    focusAreas: ["Media & Journalism", "Research & Science", "Climate & Environment"],
    geographies: ["Global"],
    stages: ["Individual / Solo", "Pre-seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.nationalgeographic.org/funding-opportunities",
    submissionType: "portal",
    portalLabel: "Apply at nationalgeographic.org/funding-opportunities",
  },
  {
    id: "solutions-journalism-network",
    name: "Solutions Journalism Network Grants",
    funder: "Solutions Journalism Network",
    awardRange: "$5K–$100K",
    eligibilitySummary:
      "Journalists and newsrooms producing rigorous reporting on responses to social problems. Supports both individual reporting projects and institutional capacity for solutions journalism.",
    focusAreas: ["Media & Journalism"],
    geographies: ["United States", "Global"],
    stages: ["Individual / Solo", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.solutionsjournalism.org/grants",
    submissionType: "portal",
    portalLabel: "Apply at solutionsjournalism.org/grants",
  },
  {
    id: "poynter-institute-grants",
    name: "Poynter Institute Fellowships & Grants",
    funder: "Poynter Institute",
    awardRange: "$2K–$20K",
    eligibilitySummary:
      "Journalists, editors, and media professionals seeking training, fellowship support, and project grants for work advancing quality, ethical journalism in the digital age.",
    focusAreas: ["Media & Journalism", "Education"],
    geographies: ["United States", "Global"],
    stages: ["Individual / Solo", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.poynter.org/training/fellowships",
    submissionType: "portal",
    portalLabel: "Apply at poynter.org/training/fellowships",
  },

  // ── Technology & Innovation ──────────────────────────────────────────────────
  {
    id: "arpa-e-open",
    name: "ARPA-E OPEN Program",
    funder: "US Dept. of Energy — Advanced Research Projects Agency-Energy",
    awardRange: "$500K–$5M",
    eligibilitySummary:
      "US entities (companies, universities, national labs) developing transformational energy technologies that have the potential to fundamentally change how we generate, store, and use energy and are too early for private investment.",
    focusAreas: ["Technology & AI", "Climate & Environment", "Research & Science"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://arpa-e.energy.gov/technologies/programs/open",
    submissionType: "portal",
    portalLabel: "Apply at arpa-e-foa.energy.gov",
  },
  {
    id: "nsf-convergence-accelerator",
    name: "NSF Convergence Accelerator",
    funder: "National Science Foundation",
    awardRange: "$750K (Phase I) – $5M (Phase II)",
    eligibilitySummary:
      "Multidisciplinary teams (academia, industry, nonprofits) building high-impact solutions to important national challenges through convergence research. Current tracks include AI, quantum, and sustainability.",
    focusAreas: ["Technology & AI", "Research & Science", "Education"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.nsf.gov/od/oia/convergence-accelerator",
    submissionType: "portal",
    portalLabel: "Apply via Research.gov",
  },
  {
    id: "in-q-tel",
    name: "In-Q-Tel (IQT) Investment",
    funder: "In-Q-Tel",
    awardRange: "$500K–$3M",
    eligibilitySummary:
      "Technology companies developing commercial products with applications relevant to US intelligence and national security community needs. Sectors include AI/ML, cybersecurity, biotech, and data analytics.",
    focusAreas: ["Technology & AI", "Research & Science"],
    geographies: ["United States"],
    stages: ["Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://www.iqt.org/work-with-us",
    submissionType: "portal",
    portalLabel: "Apply at iqt.org/work-with-us",
  },
  {
    id: "dod-sbir-sttr",
    name: "DoD SBIR/STTR Program",
    funder: "US Department of Defense",
    awardRange: "$275K (Phase I) – $1.83M (Phase II)",
    eligibilitySummary:
      "US small businesses pursuing R&D in areas of Department of Defense interest including AI, autonomy, hypersonics, biodefense, and advanced manufacturing. Largest SBIR program by funding volume.",
    focusAreas: ["Technology & AI", "Research & Science", "Other"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Series A"],
    requiresNonprofit: false,
    url: "https://www.dodsbirsttr.mil",
    submissionType: "portal",
    portalLabel: "Apply at dodsbirsttr.mil",
  },

  // ── Food, Hospitality & Agriculture ─────────────────────────────────────────
  {
    id: "james-beard-women-in-food",
    name: "James Beard Foundation Women in Food Grant",
    funder: "James Beard Foundation",
    awardRange: "$5K–$10K",
    eligibilitySummary:
      "Women working in the food industry — chefs, restaurateurs, food artisans, and culinary entrepreneurs — pursuing professional development, projects, or business growth initiatives.",
    focusAreas: ["Agriculture & Food", "Travel & Hospitality"],
    geographies: ["United States"],
    stages: ["Individual / Solo", "Seed", "Established Business"],
    requiresNonprofit: false,
    url: "https://www.jamesbeard.org/grants",
    submissionType: "portal",
    portalLabel: "Apply at jamesbeard.org/grants",
  },
  {
    id: "usda-specialty-crop-block",
    name: "USDA Specialty Crop Block Grant Program",
    funder: "US Department of Agriculture",
    awardRange: "$10K–$1M (varies by state)",
    eligibilitySummary:
      "US organizations — nonprofits, universities, and industry groups — working to enhance the competitiveness of specialty crops (fruits, vegetables, tree nuts, nursery crops). Applied through state departments of agriculture.",
    focusAreas: ["Agriculture & Food"],
    geographies: ["United States"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://www.ams.usda.gov/grants/scbgp",
    submissionType: "portal",
    portalLabel: "Apply via your state department of agriculture",
  },
  {
    id: "usda-value-added-producer",
    name: "USDA Value-Added Producer Grants",
    funder: "US Department of Agriculture",
    awardRange: "Up to $75K (planning) / $250K (working capital)",
    eligibilitySummary:
      "Independent agricultural producers, farmer cooperatives, and rural businesses developing value-added products from agricultural commodities. Must be in a rural area.",
    focusAreas: ["Agriculture & Food", "Financial Inclusion"],
    geographies: ["United States"],
    stages: ["Pre-seed", "Seed", "Established Business"],
    requiresNonprofit: false,
    url: "https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants",
    submissionType: "portal",
    portalLabel: "Apply via Grants.gov",
  },
  {
    id: "wholesome-wave-foundation",
    name: "Wholesome Wave Foundation Grants",
    funder: "Wholesome Wave Foundation",
    awardRange: "$25K–$200K",
    eligibilitySummary:
      "Organizations working to increase access to fresh, nutritious fruits and vegetables for underserved communities in the US, including SNAP-incentive programs at farmers markets.",
    focusAreas: ["Agriculture & Food", "Healthcare"],
    geographies: ["United States"],
    stages: ["Seed", "Series A", "Nonprofit"],
    requiresNonprofit: true,
    url: "https://wholesomewave.org/partnerships",
    submissionType: "portal",
    portalLabel: "Apply at wholesomewave.org/partnerships",
  },

  // ── Individual Fellowships ───────────────────────────────────────────────────
  {
    id: "macarthur-fellows",
    name: "MacArthur Fellows Program (\"Genius Grant\")",
    funder: "MacArthur Foundation",
    awardRange: "$800K over 5 years",
    eligibilitySummary:
      "Exceptionally creative individuals in any field who have shown extraordinary originality and dedication. Strictly invitation-only — nominated anonymously and selected without applicant knowledge. No application process.",
    focusAreas: ["Arts & Culture", "Research & Science", "Other"],
    geographies: ["United States"],
    stages: ["Individual / Solo"],
    requiresNonprofit: false,
    url: "https://www.macfound.org/programs/fellows",
    submissionType: "invitation",
    portalLabel: "Invitation only — no application; see macfound.org/programs/fellows",
  },
  {
    id: "acls-fellowships",
    name: "ACLS Fellowships",
    funder: "American Council of Learned Societies",
    awardRange: "$60K–$75K",
    eligibilitySummary:
      "US and Canadian faculty and independent scholars in the humanities and humanistic social sciences pursuing research resulting in significant publications. Must hold a PhD and be free of regular duties for at least 6 months.",
    focusAreas: ["Research & Science", "Arts & Culture", "Education"],
    geographies: ["United States"],
    stages: ["Individual / Solo"],
    requiresNonprofit: false,
    url: "https://www.acls.org/programs/fellowships",
    submissionType: "portal",
    portalLabel: "Apply at acls.org/programs/fellowships",
  },
  {
    id: "mellon-foundation-fellowships",
    name: "Mellon Foundation Fellowships",
    funder: "Andrew W. Mellon Foundation",
    awardRange: "$50K–$200K",
    eligibilitySummary:
      "Scholars, curators, and practitioners in the arts and humanities at universities, museums, and cultural organizations. Supports diverse voices in arts and higher education through multiple fellowship programs.",
    focusAreas: ["Arts & Culture", "Education", "Research & Science"],
    geographies: ["United States", "Global"],
    stages: ["Individual / Solo", "Nonprofit"],
    requiresNonprofit: false,
    url: "https://mellon.org/programs",
    submissionType: "portal",
    portalLabel: "Apply at mellon.org/programs",
  },
  {
    id: "rwjf-health-policy-fellows",
    name: "Robert Wood Johnson Foundation Health Policy Fellows",
    funder: "Robert Wood Johnson Foundation",
    awardRange: "Salary + benefits for 14 months",
    eligibilitySummary:
      "Mid-career health professionals, social scientists, and behavioral scientists seeking to influence federal health policy by working in Congress or federal agencies in Washington, DC.",
    focusAreas: ["Healthcare", "Research & Science"],
    geographies: ["United States"],
    stages: ["Individual / Solo"],
    requiresNonprofit: false,
    url: "https://www.rwjf.org/en/grants/active-funding-opportunities/health-policy-fellows.html",
    submissionType: "portal",
    portalLabel: "Apply at rwjf.org/health-policy-fellows",
  },
];
