export interface StateFilingInfo {
  name: string;
  abbr: string;
  /** Official name for a for-profit corporation filing */
  corpDocName: string;
  /** Official name for a nonprofit corporation filing */
  nonprofitDocName: string;
  /** Governing statute reference (for-profit) */
  corpStatute: string;
  /** Governing statute reference (nonprofit) */
  nonprofitStatute: string;
  /** Online filing portal URL */
  filingPortal: string;
  /** Label shown on the "File Online" button */
  portalLabel: string;
  /** Base filing fee for a for-profit corporation (USD) */
  corpFee: number;
  /** Base filing fee for a nonprofit corporation (USD) */
  nonprofitFee: number;
  /** Typical approval timeline */
  processingTime: string;
  /** Any special notes shown to the user */
  notes?: string;
}

const S = (
  name: string,
  abbr: string,
  corpDocName: string,
  nonprofitDocName: string,
  corpStatute: string,
  nonprofitStatute: string,
  filingPortal: string,
  portalLabel: string,
  corpFee: number,
  nonprofitFee: number,
  processingTime: string,
  notes?: string
): StateFilingInfo => ({
  name, abbr, corpDocName, nonprofitDocName,
  corpStatute, nonprofitStatute,
  filingPortal, portalLabel,
  corpFee, nonprofitFee, processingTime, notes,
});

export const STATE_REGISTRY: Record<string, StateFilingInfo> = {
  AL: S("Alabama","AL","Articles of Incorporation","Articles of Incorporation",
    "Alabama Business and Nonprofit Entities Code, §10A-2A","Alabama Business and Nonprofit Entities Code, §10A-3",
    "https://www.sos.alabama.gov/business-services/corporations","Alabama SOS",40,25,"3–5 business days"),
  AK: S("Alaska","AK","Articles of Incorporation","Articles of Incorporation",
    "Alaska Corporations Code, AS 10.06","Alaska Nonprofit Corporation Act, AS 10.20",
    "https://www.commerce.alaska.gov/web/cbpl/BusinessLicensing","Alaska CBPL",250,50,"5–10 business days"),
  AZ: S("Arizona","AZ","Articles of Incorporation","Articles of Incorporation",
    "Arizona Business Corporation Act, A.R.S. §10","Arizona Nonprofit Corporation Act, A.R.S. §10-3000",
    "https://azcc.gov/corporations/file-documents","Arizona Corporation Commission",60,40,"7–10 business days"),
  AR: S("Arkansas","AR","Articles of Incorporation","Articles of Incorporation",
    "Arkansas Business Corporation Act of 1987, A.C.A. §4-26","Arkansas Nonprofit Corporation Act, A.C.A. §4-33",
    "https://www.sos.arkansas.gov/business-commercial-services-bcs/","Arkansas SOS",50,25,"5–7 business days"),
  CA: S("California","CA","Articles of Incorporation","Articles of Incorporation",
    "California General Corporation Law, Corp. Code §100","California Nonprofit Corporation Law, Corp. Code §5000",
    "https://bizfileonline.sos.ca.gov/","California BizFile Online",100,30,"3–5 business days",
    "California requires a minimum of one director and prohibits par value stock. Nonprofits must include California-specific dissolution language."),
  CO: S("Colorado","CO","Articles of Incorporation","Articles of Incorporation",
    "Colorado Business Corporation Act, C.R.S. §7-102","Colorado Revised Nonprofit Corporation Act, C.R.S. §7-122",
    "https://www.sos.state.co.us/biz/","Colorado SOS",50,10,"1–2 business days"),
  CT: S("Connecticut","CT","Certificate of Incorporation","Certificate of Incorporation",
    "Connecticut Business Corporation Act, C.G.S. §33-600","Connecticut Revised Nonstock Corporation Act, C.G.S. §33-1000",
    "https://portal.ct.gov/SOTS/Commercial-Recording/Businesses/File-a-New-Business","Connecticut SOTS",250,50,"3–5 business days"),
  DE: S("Delaware","DE","Certificate of Incorporation","Certificate of Incorporation of a Non-Stock Corporation",
    "Delaware General Corporation Law, 8 Del. C.","Delaware General Corporation Law, 8 Del. C. §§101–115",
    "https://icis.corp.delaware.gov/ecorp/","Delaware Corp Online",89,89,"1–3 business days",
    "Most popular state for C-Corp formation. Same-day filing available for +$50."),
  FL: S("Florida","FL","Articles of Incorporation","Articles of Incorporation",
    "Florida Business Corporation Act, F.S. §607","Florida Not For Profit Corporation Act, F.S. §617",
    "https://dos.myflorida.com/sunbiz/","Florida Sunbiz",35,70,"1–3 business days",
    "Lowest filing fee in the US for for-profit corporations."),
  GA: S("Georgia","GA","Articles of Incorporation","Articles of Incorporation",
    "Georgia Business Corporation Code, O.C.G.A. §14-2","Georgia Nonprofit Corporation Code, O.C.G.A. §14-3",
    "https://sos.ga.gov/corporations","Georgia SOS",100,30,"5–7 business days"),
  HI: S("Hawaii","HI","Articles of Incorporation","Articles of Incorporation",
    "Hawaii Business Corporation Act, HRS §414","Hawaii Nonprofit Corporations Act, HRS §414D",
    "https://cca.hawaii.gov/","Hawaii CCA",50,25,"7–10 business days"),
  ID: S("Idaho","ID","Articles of Incorporation","Articles of Incorporation",
    "Idaho Business Corporation Act, I.C. §30-29","Idaho Nonprofit Corporation Act, I.C. §30-30",
    "https://sos.idaho.gov/business-services-corporation-division/","Idaho SOS",100,30,"3–5 business days"),
  IL: S("Illinois","IL","Articles of Incorporation","Articles of Incorporation",
    "Illinois Business Corporation Act, 805 ILCS 5","Illinois General Not For Profit Corporation Act, 805 ILCS 105",
    "https://apps.ilsos.gov/","Illinois SOS",150,50,"5–10 business days"),
  IN: S("Indiana","IN","Articles of Incorporation","Articles of Incorporation",
    "Indiana Business Corporation Law, IC §23-1","Indiana Nonprofit Corporation Act, IC §23-17",
    "https://inbiz.in.gov/","Indiana INBiz",95,30,"1–3 business days"),
  IA: S("Iowa","IA","Articles of Incorporation","Articles of Incorporation",
    "Iowa Business Corporation Act, Iowa Code §490","Iowa Revised Model Nonprofit Corporation Act, Iowa Code §504",
    "https://sos.iowa.gov/","Iowa SOS",50,20,"3–5 business days"),
  KS: S("Kansas","KS","Articles of Incorporation","Articles of Incorporation",
    "Kansas General Corporation Code, K.S.A. §17-6001","Kansas General Corporation Code (nonprofit), K.S.A. §17-6002",
    "https://www.sos.ks.gov/","Kansas SOS",90,20,"3–5 business days"),
  KY: S("Kentucky","KY","Articles of Incorporation","Articles of Incorporation",
    "Kentucky Business Corporation Act, KRS §271B","Kentucky Nonprofit Corporation Act, KRS §273",
    "https://sos.ky.gov/","Kentucky SOS",40,8,"3–5 business days"),
  LA: S("Louisiana","LA","Articles of Incorporation","Articles of Incorporation",
    "Louisiana Business Corporation Act, La. R.S. §12:1","Louisiana Nonprofit Corporation Law, La. R.S. §12:201",
    "https://www.sos.la.gov/","Louisiana SOS",75,75,"3–5 business days"),
  ME: S("Maine","ME","Articles of Incorporation","Articles of Incorporation",
    "Maine Business Corporation Act, 13-C M.R.S.A.","Maine Nonprofit Corporation Act, 13-B M.R.S.A.",
    "https://www.maine.gov/sos/cec/corp/","Maine SOS",145,40,"5–7 business days"),
  MD: S("Maryland","MD","Articles of Incorporation","Articles of Incorporation",
    "Maryland General Corporation Law, Md. Code §2-101","Maryland General Corporation Law (nonprofits), Md. Code §5-101",
    "https://egov.maryland.gov/BusinessExpress/","Maryland Business Express",120,100,"7–10 business days"),
  MA: S("Massachusetts","MA","Articles of Organization","Articles of Organization",
    "Massachusetts Business Corporation Act, M.G.L. c. 156D","Massachusetts Nonprofit Corporation Act, M.G.L. c. 180",
    "https://corp.sec.state.ma.us/","Massachusetts Corporations",275,35,"3–5 business days"),
  MI: S("Michigan","MI","Articles of Incorporation","Articles of Incorporation",
    "Michigan Business Corporation Act, MCL §450.1001","Michigan Nonprofit Corporation Act, MCL §450.2001",
    "https://www.michigan.gov/lara/","Michigan LARA",50,20,"5–7 business days"),
  MN: S("Minnesota","MN","Articles of Incorporation","Articles of Incorporation",
    "Minnesota Business Corporation Act, Minn. Stat. §302A","Minnesota Nonprofit Corporation Act, Minn. Stat. §317A",
    "https://www.sos.state.mn.us/","Minnesota SOS",135,70,"5–7 business days"),
  MS: S("Mississippi","MS","Articles of Incorporation","Articles of Incorporation",
    "Mississippi Business Corporation Act, Miss. Code §79-4","Mississippi Nonprofit Corporation Act, Miss. Code §79-11",
    "https://www.sos.ms.gov/","Mississippi SOS",50,50,"5–7 business days"),
  MO: S("Missouri","MO","Articles of Incorporation","Articles of Incorporation",
    "Missouri General and Business Corporation Law, RSMo §351","Missouri Nonprofit Corporation Law, RSMo §355",
    "https://www.sos.mo.gov/","Missouri SOS",58,25,"3–5 business days"),
  MT: S("Montana","MT","Articles of Incorporation","Articles of Incorporation",
    "Montana Business Corporation Act, MCA §35-1","Montana Nonprofit Corporation Act, MCA §35-2",
    "https://sos.mt.gov/","Montana SOS",70,20,"5–7 business days"),
  NE: S("Nebraska","NE","Articles of Incorporation","Articles of Incorporation",
    "Nebraska Business Corporation Act, Neb. Rev. Stat. §21-2","Nebraska Nonprofit Corporation Act, Neb. Rev. Stat. §21-19",
    "https://www.sos.ne.gov/","Nebraska SOS",65,10,"3–5 business days"),
  NV: S("Nevada","NV","Articles of Incorporation","Articles of Incorporation",
    "Nevada Revised Statutes, NRS §78","Nevada Revised Statutes (nonprofits), NRS §82",
    "https://esos.nv.gov/","Nevada SOS",75,50,"1–2 business days",
    "Nevada requires an Initial List of Officers filing ($200) due within 30 days of incorporation. Total first-year cost: ~$275."),
  NH: S("New Hampshire","NH","Articles of Incorporation","Articles of Incorporation",
    "New Hampshire Business Corporation Act, RSA §293-A","New Hampshire Nonprofit Corporation Act, RSA §292",
    "https://www.sos.nh.gov/","New Hampshire SOS",100,25,"3–5 business days"),
  NJ: S("New Jersey","NJ","Certificate of Incorporation","Certificate of Incorporation",
    "New Jersey Business Corporation Act, N.J.S.A. §14A","New Jersey Nonprofit Corporation Act, N.J.S.A. §15A",
    "https://www.njportal.com/DOR/businessformation/","New Jersey Business Formation",125,75,"3–5 business days"),
  NM: S("New Mexico","NM","Articles of Incorporation","Articles of Incorporation",
    "New Mexico Business Corporation Act, NMSA §53-11","New Mexico Nonprofit Corporation Act, NMSA §53-8",
    "https://www.sos.nm.gov/","New Mexico SOS",50,25,"5–7 business days"),
  NY: S("New York","NY","Certificate of Incorporation","Certificate of Incorporation",
    "New York Business Corporation Law, N.Y. Bus. Corp. Law","New York Not-for-Profit Corporation Law, N.Y. N-PCL",
    "https://apps.dos.ny.gov/","New York DOS",125,75,"7–14 business days",
    "New York requires the Certificate to specify the county of the registered office. Nonprofit requires specific N-PCL §404 purpose language."),
  NC: S("North Carolina","NC","Articles of Incorporation","Articles of Incorporation",
    "North Carolina Business Corporation Act, N.C.G.S. §55","North Carolina Nonprofit Corporation Act, N.C.G.S. §55A",
    "https://www.sosnc.gov/","North Carolina SOS",125,60,"3–5 business days"),
  ND: S("North Dakota","ND","Articles of Incorporation","Articles of Incorporation",
    "North Dakota Business Corporation Act, N.D.C.C. §10-19.1","North Dakota Nonprofit Corporation Act, N.D.C.C. §10-33",
    "https://firststop.sos.nd.gov/","North Dakota FirstStop",100,40,"3–5 business days"),
  OH: S("Ohio","OH","Articles of Incorporation","Articles of Incorporation",
    "Ohio General Corporation Law, O.R.C. §1701","Ohio Nonprofit Corporation Law, O.R.C. §1702",
    "https://www.sos.state.oh.us/","Ohio SOS",99,99,"3–5 business days"),
  OK: S("Oklahoma","OK","Articles of Incorporation","Certificate of Incorporation",
    "Oklahoma General Corporation Act, 18 O.S. §1001","Oklahoma Statutes, 18 O.S. §1100",
    "https://www.sos.ok.gov/","Oklahoma SOS",50,25,"3–5 business days"),
  OR: S("Oregon","OR","Articles of Incorporation","Articles of Incorporation",
    "Oregon Business Corporation Act, ORS §60","Oregon Nonprofit Corporation Act, ORS §65",
    "https://sos.oregon.gov/","Oregon SOS",100,50,"1–3 business days"),
  PA: S("Pennsylvania","PA","Articles of Incorporation","Articles of Incorporation",
    "Pennsylvania Business Corporation Law, 15 Pa. C.S. §1000","Pennsylvania Nonprofit Corporation Law, 15 Pa. C.S. §5000",
    "https://www.dos.pa.gov/","Pennsylvania DOS",125,70,"3–7 business days"),
  RI: S("Rhode Island","RI","Articles of Incorporation","Articles of Incorporation",
    "Rhode Island Business Corporation Act, R.I. Gen. Laws §7-1.2","Rhode Island Nonprofit Corporation Act, R.I. Gen. Laws §7-6",
    "https://www.sos.ri.gov/","Rhode Island SOS",230,35,"3–5 business days"),
  SC: S("South Carolina","SC","Articles of Incorporation","Articles of Incorporation",
    "South Carolina Business Corporation Act, S.C. Code §33-1","South Carolina Nonprofit Corporation Act, S.C. Code §33-31",
    "https://sos.sc.gov/","South Carolina SOS",135,25,"5–7 business days"),
  SD: S("South Dakota","SD","Articles of Incorporation","Articles of Incorporation",
    "South Dakota Business Corporation Act, SDCL §47-1A","South Dakota Nonprofit Corporation Act, SDCL §47-22",
    "https://sdsos.gov/","South Dakota SOS",150,30,"3–5 business days"),
  TN: S("Tennessee","TN","Charter","Charter",
    "Tennessee Business Corporation Act, T.C.A. §48-11","Tennessee Nonprofit Corporation Act, T.C.A. §48-51",
    "https://tnbear.tn.gov/","Tennessee BEAR",100,100,"3–5 business days",
    "Tennessee uses the term 'Charter' instead of Articles or Certificate."),
  TX: S("Texas","TX","Certificate of Formation","Certificate of Formation",
    "Texas Business Organizations Code, Tex. Bus. Org. Code §21","Texas Business Organizations Code (nonprofits), Tex. Bus. Org. Code §22",
    "https://www.sos.state.tx.us/","Texas SOS",300,25,"3–5 business days",
    "Texas uses 'Certificate of Formation' for all entity types. Highest for-profit filing fee in the US."),
  UT: S("Utah","UT","Articles of Incorporation","Articles of Incorporation",
    "Utah Revised Business Corporation Act, U.C.A. §16-10a","Utah Revised Nonprofit Corporation Act, U.C.A. §16-6a",
    "https://corps.utah.gov/","Utah Corporations",70,30,"1–3 business days"),
  VT: S("Vermont","VT","Articles of Incorporation","Articles of Incorporation",
    "Vermont Business Corporation Act, 11A V.S.A.","Vermont Nonprofit Corporation Act, 11B V.S.A.",
    "https://www.sos.vermont.gov/","Vermont SOS",125,75,"3–5 business days"),
  VA: S("Virginia","VA","Articles of Incorporation","Articles of Incorporation",
    "Virginia Stock Corporation Act, Va. Code §13.1-601","Virginia Nonstock Corporation Act, Va. Code §13.1-801",
    "https://www.scc.virginia.gov/","Virginia SCC",25,75,"1–3 business days",
    "Virginia has the lowest for-profit corporation filing fee at just $25."),
  WA: S("Washington","WA","Articles of Incorporation","Articles of Incorporation",
    "Washington Business Corporation Act, RCW §23B","Washington Nonprofit Corporation Act, RCW §24.03A",
    "https://ccfs.sos.wa.gov/","Washington SOS",180,30,"1–3 business days"),
  WV: S("West Virginia","WV","Articles of Incorporation","Articles of Incorporation",
    "West Virginia Business Corporation Act, W. Va. Code §31D","West Virginia Nonprofit Corporation Act, W. Va. Code §31E",
    "https://sos.wv.gov/","West Virginia SOS",65,15,"5–7 business days"),
  WI: S("Wisconsin","WI","Articles of Incorporation","Articles of Incorporation",
    "Wisconsin Business Corporation Law, Wis. Stat. §180","Wisconsin Nonstock Corporation Law, Wis. Stat. §181",
    "https://www.wdfi.org/","Wisconsin DFI",100,35,"3–5 business days"),
  WY: S("Wyoming","WY","Articles of Incorporation","Articles of Incorporation",
    "Wyoming Business Corporation Act, W.S. §17-16","Wyoming Nonprofit Corporation Act, W.S. §17-19",
    "https://wyobiz.wyo.gov/","Wyoming SOS",100,25,"1–2 business days",
    "Popular alternative to Delaware — no state income tax, strong asset protection laws, low annual fees."),
  DC: S("District of Columbia","DC","Articles of Incorporation","Articles of Incorporation",
    "DC Business Organization Code, D.C. Code §29-3","DC Nonprofit Corporation Act, D.C. Code §29-4",
    "https://dcbiz.dc.gov/","DC BEGA",99,80,"5–10 business days"),
};

export const STATES_LIST = Object.values(STATE_REGISTRY).sort((a, b) =>
  a.name.localeCompare(b.name)
);

export function getState(abbr: string): StateFilingInfo | undefined {
  return STATE_REGISTRY[abbr];
}
