import type { CompanyProfile, ScoredGrant } from "@/lib/types";

interface SubmitRequest {
  profile: CompanyProfile;
  grant: ScoredGrant;
  pitch: string;
  factChecks: string[];
  applicantName: string;
  applicantEmail: string;
}

export async function POST(request: Request) {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) throw new Error("RESEND_API_KEY is not set");

  const { profile, grant, pitch, factChecks, applicantName, applicantEmail }: SubmitRequest =
    await request.json();

  const isEmailGrant = grant.submissionType === "email" && grant.submissionEmail;
  const isInvitationGrant = grant.submissionType === "invitation";

  const factCheckHtml =
    factChecks.length > 0
      ? `<div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:8px;padding:20px;margin:24px 0;">
          <h3 style="margin:0 0 12px;color:#92400e;font-size:15px;">⚠️ Fact-check before submitting</h3>
          <ul style="margin:0;padding-left:20px;color:#78350f;">
            ${factChecks.map((f) => `<li style="margin-bottom:8px;font-size:14px;">${f}</li>`).join("")}
          </ul>
        </div>`
      : "";

  const pitchHtml = pitch
    .split("\n\n")
    .map((p) => `<p style="margin:0 0 16px;color:#1f2937;line-height:1.7;font-size:15px;">${p.replace(/\n/g, "<br>")}</p>`)
    .join("");

  const submissionInstructions = isEmailGrant
    ? `<div style="background:#ecfdf5;border:1px solid #6ee7b7;border-radius:8px;padding:20px;margin:24px 0;">
        <h3 style="margin:0 0 8px;color:#065f46;font-size:15px;">📤 How to submit</h3>
        <p style="margin:0;color:#047857;font-size:14px;">
          Send this pitch to <strong>${grant.submissionEmail}</strong> — use the subject line below and attach any required documents from their guidelines.
        </p>
        <p style="margin:12px 0 0;color:#047857;font-size:14px;">
          <strong>Suggested subject:</strong> Grant Application: ${profile.companyName} — ${grant.name}
        </p>
      </div>`
    : isInvitationGrant
    ? `<div style="background:#f0f9ff;border:1px solid #7dd3fc;border-radius:8px;padding:20px;margin:24px 0;">
        <h3 style="margin:0 0 8px;color:#0c4a6e;font-size:15px;">📋 Nomination required</h3>
        <p style="margin:0;color:#0369a1;font-size:14px;">
          This grant is invite/nomination-only. Visit <a href="${grant.url}" style="color:#0369a1;">${grant.url}</a> to submit a nomination or request an introduction through your network.
        </p>
      </div>`
    : `<div style="background:#f0f9ff;border:1px solid #7dd3fc;border-radius:8px;padding:20px;margin:24px 0;">
        <h3 style="margin:0 0 8px;color:#0c4a6e;font-size:15px;">📋 Next step: submit via portal</h3>
        <p style="margin:0;color:#0369a1;font-size:14px;">
          Copy your pitch above and paste it into the application form at:<br>
          <a href="${grant.url}" style="color:#0369a1;font-weight:600;">${grant.portalLabel ?? grant.url}</a>
        </p>
      </div>`;

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f9fafb;margin:0;padding:0;">
  <div style="max-width:640px;margin:0 auto;padding:32px 16px;">
    <div style="background:#ffffff;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden;">
      <div style="background:#1a5c3a;padding:24px 32px;">
        <p style="margin:0 0 4px;color:#a7f3d0;font-size:12px;font-weight:600;letter-spacing:0.05em;text-transform:uppercase;">Founder Kit · Grant Application</p>
        <h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:700;">${grant.name}</h1>
        <p style="margin:6px 0 0;color:#d1fae5;font-size:14px;">${grant.funder} · ${grant.awardRange}</p>
      </div>
      <div style="padding:32px;">
        <p style="margin:0 0 24px;color:#6b7280;font-size:14px;">
          Hi ${applicantName}, here is your AI-generated pitch for <strong>${profile.companyName}</strong>. Review and fact-check before submitting.
        </p>

        ${submissionInstructions}

        <div style="border:1px solid #e5e7eb;border-radius:8px;padding:24px;margin-bottom:24px;">
          <h2 style="margin:0 0 20px;color:#111827;font-size:16px;font-weight:700;border-bottom:1px solid #f3f4f6;padding-bottom:12px;">Your Pitch Draft</h2>
          ${pitchHtml}
        </div>

        ${factCheckHtml}

        <div style="border-top:1px solid #f3f4f6;padding-top:20px;margin-top:8px;">
          <p style="margin:0;color:#9ca3af;font-size:12px;">Generated by <a href="https://myfounderkit.com" style="color:#1a5c3a;text-decoration:none;">Founder Kit</a> · Always verify AI-generated content before submitting to funders.</p>
        </div>
      </div>
    </div>
  </div>
</body>
</html>`;

  const toAddresses = [applicantEmail];
  if (isEmailGrant && grant.submissionEmail) {
    toAddresses.push(grant.submissionEmail);
  }

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: "Founder Kit <grants@bannermanmenson.com>",
      to: toAddresses,
      reply_to: applicantEmail,
      subject: `Grant Application: ${profile.companyName} — ${grant.name}`,
      html,
    }),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    console.error("Resend error:", res.status, text);
    return Response.json({ error: "Internal server error" }, { status: 500 });
  }

  return Response.json({
    ok: true,
    sentToFunder: isEmailGrant,
    funderEmail: isEmailGrant ? grant.submissionEmail : null,
    portalUrl: !isEmailGrant ? grant.url : null,
  });
}
