export const metadata = {
  title: "Privacy Policy — Founder Kit",
  description: "How Founder Kit collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <div className="max-w-2xl mx-auto py-8">
      <h1 className="text-2xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: June 17, 2026</p>

      <div className="prose prose-sm text-gray-700 space-y-6">
        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">1. What we collect</h2>
          <p>We collect your name, email address, and password (hashed with PBKDF2 — never stored in plain text) when you create an account. When you use the Grant Automator, we store your organization profile fields (company name, focus area, geography, etc.) to score grants and generate pitches. We do not store payment card numbers — Stripe handles all payment processing.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">2. How we use your data</h2>
          <ul className="list-disc pl-4 space-y-1">
            <li>To provide the services: grant matching, pitch generation, formation documents, and federal registration guidance.</li>
            <li>To send transactional emails (welcome, password reset, pitch delivery) via Resend.</li>
            <li>To track monthly usage (searches and pitch generations) and enforce plan limits.</li>
            <li>To process payments and manage subscriptions via Stripe.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">3. Third-party services</h2>
          <ul className="list-disc pl-4 space-y-1">
            <li><strong>Stripe</strong> — payment processing. Subject to Stripe&apos;s privacy policy.</li>
            <li><strong>Resend</strong> — transactional email delivery.</li>
            <li><strong>Exa</strong> — live web search for grant discovery. Your organization profile is sent to Exa to perform searches.</li>
            <li><strong>OpenRouter / Google Gemini</strong> — AI grant scoring and pitch generation. Your profile is sent to these services.</li>
            <li><strong>Neon</strong> — hosted PostgreSQL database (AWS Frankfurt region).</li>
            <li><strong>Vercel</strong> — hosting and deployment.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">4. Data retention</h2>
          <p>We retain your account data for as long as your account exists. You may request deletion by emailing <a href="mailto:hello@myfounderkit.com" className="text-[#1a5c3a] underline">hello@myfounderkit.com</a>. Usage event records are retained for 13 months to enforce monthly limits. Password reset tokens expire after 1 hour and are deleted on use.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">5. Cookies</h2>
          <p>We set a single httpOnly session cookie (<code>app_session</code>) after login. It expires when you log out. We do not use advertising or tracking cookies.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">6. AI-generated content</h2>
          <p>Grant pitches, formation documents, and registration checklists are generated by AI and may contain errors. They are not legal advice. Always verify with a licensed attorney before filing or submitting to funders.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">7. Contact</h2>
          <p>Questions or deletion requests: <a href="mailto:hello@myfounderkit.com" className="text-[#1a5c3a] underline">hello@myfounderkit.com</a></p>
        </section>
      </div>
    </div>
  );
}
