export const metadata = {
  title: "Terms of Service — Founder Kit",
  description: "Terms governing your use of Founder Kit.",
};

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto py-8">
      <h1 className="text-2xl font-bold text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: June 17, 2026</p>

      <div className="prose prose-sm text-gray-700 space-y-6">
        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">1. Acceptance</h2>
          <p>By creating a Founder Kit account or using any part of myfounderkit.com, you agree to these Terms. If you do not agree, do not use the service.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">2. Service description</h2>
          <p>Founder Kit provides AI-assisted tools for grant discovery, pitch drafting, entity formation document generation, and federal registration guidance. All outputs are generated by artificial intelligence and are provided for informational purposes only.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">3. Not legal or financial advice</h2>
          <p>Nothing produced by Founder Kit — including formation documents, pitch letters, registration checklists, or grant recommendations — constitutes legal, financial, or professional advice. You are solely responsible for verifying all AI-generated content with qualified professionals before filing, submitting, or relying on it. Founder Kit is not a law firm and is not a substitute for an attorney.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">4. Account and billing</h2>
          <ul className="list-disc pl-4 space-y-1">
            <li>You must be 18 or older and have legal capacity to enter contracts.</li>
            <li>Free accounts include 5 grant searches and 10 pitch drafts per calendar month.</li>
            <li>Pro accounts are billed monthly at $19 USD via Stripe. Cancellation takes effect at the end of the current billing period. No refunds for partial months.</li>
            <li>You are responsible for keeping your login credentials secure.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">5. Acceptable use</h2>
          <p>You may not use Founder Kit to submit fraudulent grant applications, misrepresent your organization to funders, or violate any applicable law. We reserve the right to suspend accounts that abuse the service or violate these terms.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">6. Disclaimers and limitation of liability</h2>
          <p>Founder Kit is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that grant matches are accurate, complete, or that applying to any grant will result in funding. To the maximum extent permitted by law, Founder Kit&apos;s liability to you for any claim arising from use of the service is limited to the amount you paid us in the 12 months preceding the claim.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">7. Intellectual property</h2>
          <p>You retain ownership of any content you submit (organization name, description, etc.). AI-generated outputs (pitch drafts, formation documents) are yours to use. Founder Kit retains ownership of the platform, software, and underlying grant database.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">8. Changes and termination</h2>
          <p>We may update these Terms at any time. Material changes will be communicated by email. Continued use after changes constitutes acceptance. We may suspend or terminate accounts for violations with reasonable notice except in cases of fraud or abuse.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">9. Governing law</h2>
          <p>These Terms are governed by the laws of the State of Delaware, without regard to conflict of law provisions.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">10. Contact</h2>
          <p><a href="mailto:hello@myfounderkit.com" className="text-[#1a5c3a] underline">hello@myfounderkit.com</a></p>
        </section>
      </div>
    </div>
  );
}
